apiVersion: v1
kind: Secret
metadata:
  name: httpserver-secret
type: Opaque
data:
  httpserver-password-hash-secret: dHdpY2Vfc2VjdXJpdHlfMDE= # Nobody uses this in prod.
  httpserver-token-hmac-secret: dHdpY2Vfc2VjdXJpdHlfMDI=    # Nobody uses this in prod.