apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cluster-persistent-volume-claim
  name: cluster-persistent-volume-claim
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi